# Generated by Django 4.2.7 on 2026-01-11 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0003_add_user_to_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_obj',
            field=models.ForeignKey(blank=True, db_column='class_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='teacher.class', verbose_name='所属班级'),
        ),
    ]
