# Generated by Django 4.2.7 on 2026-01-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_add_class_id_to_student'),
    ]

    operations = [
        # 只保留添加class_name字段的操作，跳过其他可能导致错误的操作
        migrations.AddField(
            model_name='student',
            name='class_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='所属班级'),
        ),
    ]
