# Generated by Django 5.2 on 2026-01-11 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_add_class_name_to_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_obj',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='is_active',
        ),
    ]
