# Generated by Django 4.2.7 on 2026-01-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_remove_student_student_class_i_c7140f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlearningprogress',
            name='learn_time',
            field=models.IntegerField(default=0, verbose_name='学习时长（分钟）'),
        ),
    ]
