# Generated by Django 4.2.7 on 2026-01-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_add_learn_time_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlearningprogress',
            name='learn_status',
            field=models.IntegerField(default=1, verbose_name='学习状态', help_text='1-未学习，2-学习中，3-已完成'),
        ),
    ]
