# Generated by Django 4.2.7 on 2026-01-11 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_remove_book_introduction'),
        ('teacher', '0008_add_learn_status_column'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studentlearningprogress',
            index=models.Index(fields=['student'], name='student_lea_student_01345e_idx'),
        ),
        migrations.AddIndex(
            model_name='studentlearningprogress',
            index=models.Index(fields=['chapter'], name='student_lea_chapter_c36c49_idx'),
        ),
    ]
