# Generated by Django 5.2 on 2026-01-12 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_alter_book_current_version'),
        ('teacher', '0009_remove_student_student_class_i_c7140f_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachingtoollog',
            name='class_obj',
        ),
        migrations.RemoveField(
            model_name='teachingtoollog',
            name='teacher',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='student_class_i_c7140f_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentlearningprogress',
            name='student_lea_teacher_a5cb24_idx',
        ),
        migrations.RemoveField(
            model_name='studentlearningprogress',
            name='teacher',
        ),
        migrations.AddField(
            model_name='studentlearningprogress',
            name='book',
            field=models.ForeignKey(blank=True, db_column='book_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='books.book', verbose_name='教材'),
        ),
        migrations.AddField(
            model_name='studentlearningprogress',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='是否已完成'),
        ),
        migrations.AddField(
            model_name='studentlearningprogress',
            name='progress',
            field=models.FloatField(default=0, verbose_name='学习进度'),
        ),
        migrations.AlterField(
            model_name='studentlearningprogress',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='TeachingToolLog',
        ),
    ]
