# Generated by Django 4.2.7 on 2026-01-12 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_fix_teachingresource_teacher_fk'),
        ('teacher', '0009_remove_student_student_class_i_c7140f_idx_and_more'),
    ]

    operations = [
    ]
