# Generated by Django 4.2.7 on 2026-01-12 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_remove_book_introduction'),
        ('teacher', '0010_merge_20260112_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(db_column='report_id', primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('student', '学生个人报告'), ('class', '班级整体报告'), ('comparison', '对比分析报告')], max_length=20, verbose_name='报告类型')),
                ('title', models.CharField(max_length=200, verbose_name='报告标题')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('include_progress', models.BooleanField(default=True, verbose_name='包含学习进度')),
                ('include_homework', models.BooleanField(default=True, verbose_name='包含作业完成情况')),
                ('include_attendance', models.BooleanField(default=False, verbose_name='包含出勤统计')),
                ('include_performance', models.BooleanField(default=True, verbose_name='包含成绩分析')),
                ('export_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('word', 'Word')], default='pdf', max_length=10, verbose_name='导出格式')),
                ('report_data', models.JSONField(blank=True, null=True, verbose_name='报告数据')),
                ('file_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='报告文件路径')),
                ('status', models.IntegerField(default=1, help_text='1-生成中，2-已完成，3-生成失败', verbose_name='状态')),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_column='create_time', verbose_name='生成时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='update_time', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '报告',
                'verbose_name_plural': '报告',
                'db_table': 'report',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.RemoveField(
            model_name='teachingtoollog',
            name='class_obj',
        ),
        migrations.RemoveField(
            model_name='teachingtoollog',
            name='teacher',
        ),
        migrations.AlterModelOptions(
            name='studenthomework',
            options={'managed': False, 'verbose_name': '学生作业提交', 'verbose_name_plural': '学生作业提交'},
        ),
        migrations.AlterModelOptions(
            name='teachingresource',
            options={'ordering': ['-created_at'], 'verbose_name': '教学资源', 'verbose_name_plural': '教学资源'},
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='student_class_i_c7140f_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentlearningprogress',
            name='student_lea_teacher_a5cb24_idx',
        ),
        migrations.RemoveIndex(
            model_name='teachingresource',
            name='teaching_re_chapter_2ecbfb_idx',
        ),
        migrations.RenameIndex(
            model_name='classresource',
            new_name='class_resou_file_ha_2671fd_idx',
            old_name='class_resou_file_h_ix',
        ),
        migrations.RenameIndex(
            model_name='classresource',
            new_name='class_resou_upload__18774b_idx',
            old_name='class_resou_upload__ix',
        ),
        migrations.RenameIndex(
            model_name='teachingresource',
            new_name='teacher_tea_teacher_c7a90b_idx',
            old_name='teaching_re_teacher_971adc_idx',
        ),
        migrations.RenameIndex(
            model_name='teachingresource',
            new_name='teacher_tea_file_ha_6531ff_idx',
            old_name='teacher_tea_file_h_ix',
        ),
        migrations.RenameIndex(
            model_name='teachingresource',
            new_name='teacher_tea_upload__58d5a1_idx',
            old_name='teacher_tea_upload__ix',
        ),
        migrations.RemoveField(
            model_name='studentlearningprogress',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='teachingresource',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='teachingresource',
            name='resource_desc',
        ),
        migrations.RemoveField(
            model_name='teachingresource',
            name='resource_name',
        ),
        migrations.RemoveField(
            model_name='teachingresource',
            name='resource_url',
        ),
        migrations.RemoveField(
            model_name='teachingresource',
            name='upload_time',
        ),
        migrations.AddField(
            model_name='studentlearningprogress',
            name='book',
            field=models.ForeignKey(blank=True, db_column='book_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='books.book', verbose_name='教材'),
        ),
        migrations.AddField(
            model_name='studentlearningprogress',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='是否已完成'),
        ),
        migrations.AddField(
            model_name='studentlearningprogress',
            name='progress',
            field=models.FloatField(default=0, verbose_name='学习进度'),
        ),
        migrations.AddField(
            model_name='teachingresource',
            name='category',
            field=models.CharField(blank=True, db_column='category', max_length=100, null=True, verbose_name='资源分类'),
        ),
        migrations.AddField(
            model_name='teachingresource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='teachingresource',
            name='description',
            field=models.TextField(blank=True, db_column='description', null=True, verbose_name='资源描述'),
        ),
        migrations.AddField(
            model_name='teachingresource',
            name='is_public',
            field=models.BooleanField(db_column='is_public', default=True, verbose_name='是否公开'),
        ),
        migrations.AddField(
            model_name='teachingresource',
            name='title',
            field=models.CharField(db_column='title', default='未命名资源', max_length=200, verbose_name='资源标题'),
        ),
        migrations.AddField(
            model_name='teachingresource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at', null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='studentlearningprogress',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teachingresource',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teachingresource',
            name='resource_type',
            field=models.CharField(db_column='resource_type', default='file', max_length=20, verbose_name='资源类型'),
        ),
        migrations.AlterModelTable(
            name='teachingresource',
            table='teacher_teachingresource',
        ),
        migrations.DeleteModel(
            name='TeachingToolLog',
        ),
        migrations.AddField(
            model_name='report',
            name='class_obj',
            field=models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='teacher.class', verbose_name='所属班级'),
        ),
        migrations.AddField(
            model_name='report',
            name='student',
            field=models.ForeignKey(blank=True, db_column='student_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='teacher.student', verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='report',
            name='teacher',
            field=models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='teacher.teacher', verbose_name='生成教师'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['teacher'], name='report_teacher_43b12b_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['class_obj'], name='report_class_i_e65080_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['student'], name='report_student_f6df50_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type'], name='report_report__a84470_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='report_status_74972f_idx'),
        ),
    ]
