# Generated by Django 4.2.7 on 2026-01-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_report_remove_teachingtoollog_class_obj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='is_important',
            field=models.BooleanField(default=False, verbose_name='是否重要'),
        ),
        migrations.AddField(
            model_name='notice',
            name='type',
            field=models.CharField(choices=[('system', '系统通知'), ('assignment', '作业提醒'), ('student', '学生消息'), ('announcement', '公告')], default='announcement', max_length=20, verbose_name='通知类型'),
        ),
    ]
