# Generated by Django 4.2.7 on 2026-01-12 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_notice_is_important_notice_type'),
    ]

    operations = [
        # 为is_important字段添加默认值
        migrations.RunSQL(
            sql='ALTER TABLE notice MODIFY COLUMN is_important BOOLEAN NOT NULL DEFAULT FALSE;',
            reverse_sql='ALTER TABLE notice MODIFY COLUMN is_important BOOLEAN;'
        ),
        # 为type字段添加默认值
        migrations.RunSQL(
            sql="ALTER TABLE notice MODIFY COLUMN type VARCHAR(20) NOT NULL DEFAULT 'announcement';",
            reverse_sql='ALTER TABLE notice MODIFY COLUMN type VARCHAR(20);'
        ),
    ]
