# Generated by Django 4.2.7 on 2026-01-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0013_add_default_values_to_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(db_column='student_class_id', primary_key=True, serialize=False)),
                ('student', models.BigIntegerField(db_column='student_id', verbose_name='学生ID')),
                ('class_obj', models.BigIntegerField(db_column='class_id', verbose_name='班级ID')),
                ('is_active', models.BooleanField(default=True, help_text='True-在班，False-已退班', verbose_name='是否有效')),
                ('joined_at', models.DateTimeField(auto_now_add=True, db_column='join_time', verbose_name='加入时间')),
                ('left_at', models.DateTimeField(blank=True, db_column='leave_time', null=True, verbose_name='离开时间')),
            ],
            options={
                'verbose_name': '学生班级关系',
                'verbose_name_plural': '学生班级关系',
                'db_table': 'student_class',
                'ordering': ['-joined_at'],
            },
        ),
    ]
