# Generated by Django 4.2.7 on 2026-01-12 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0014_studentclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='course_code',
            field=models.CharField(blank=True, help_text='用于学生加入班级的唯一码', max_length=20, null=True, unique=True, verbose_name='课程码'),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='class_obj',
            field=models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='student_classes', to='teacher.class', verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='student_classes', to='teacher.student', verbose_name='学生'),
        ),
    ]
