# Generated by Django 4.2.7 on 2026-01-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0015_class_course_code_alter_studentclass_class_obj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='class_obj',
            field=models.IntegerField(db_column='class_id', verbose_name='班级ID'),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='student',
            field=models.IntegerField(db_column='student_id', verbose_name='学生ID'),
        ),
    ]
