# Generated by Django 4.2.7 on 2026-01-13 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0016_alter_studentclass_class_obj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='class_obj',
            field=models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='student_classes', to='teacher.class', verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='student_classes', to='teacher.student', verbose_name='学生'),
        ),
        migrations.CreateModel(
            name='StudentHomeworkFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_path', models.CharField(max_length=255, verbose_name='文件存储路径')),
                ('storage_path', models.TextField(blank=True, db_column='storage_path', null=True, verbose_name='完整存储路径')),
                ('file_size', models.BigIntegerField(db_column='file_size', verbose_name='文件大小（字节）')),
                ('file_hash', models.CharField(blank=True, db_column='file_hash', max_length=64, null=True, verbose_name='文件哈希值')),
                ('mime_type', models.CharField(blank=True, db_column='mime_type', max_length=100, null=True, verbose_name='文件MIME类型')),
                ('upload_status', models.CharField(choices=[('uploading', '上传中'), ('completed', '已完成'), ('failed', '失败')], db_column='upload_status', default='completed', max_length=20, verbose_name='上传状态')),
                ('upload_time', models.DateTimeField(auto_now_add=True, db_column='upload_time', verbose_name='上传时间')),
                ('upload_ip', models.GenericIPAddressField(blank=True, db_column='upload_ip', null=True, verbose_name='上传IP地址')),
                ('student_homework', models.ForeignKey(db_column='student_homework_id', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='teacher.studenthomework', verbose_name='作业提交')),
            ],
            options={
                'verbose_name': '学生作业文件',
                'verbose_name_plural': '学生作业文件',
                'db_table': 'student_homework_file',
                'indexes': [models.Index(fields=['student_homework'], name='student_hom_student_0b87fc_idx'), models.Index(fields=['file_hash'], name='student_hom_file_ha_879d2b_idx')],
            },
        ),
    ]
