# Generated by Django 4.2.7 on 2025-11-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='title',
        ),
        migrations.AddField(
            model_name='tool',
            name='name',
            field=models.CharField(default='未命名工具', max_length=100, verbose_name='工具名称'),
        ),
        migrations.AddField(
            model_name='tool',
            name='slug',
            field=models.SlugField(default='default-tool', max_length=100, unique=True, verbose_name='工具标识'),
        ),
        migrations.AddField(
            model_name='toolcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='description',
            field=models.TextField(default='', verbose_name='工具描述'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='implementation_class',
            field=models.CharField(default='', max_length=100, verbose_name='实现类名'),
        ),
        migrations.AlterField(
            model_name='toolcategory',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='分类描述'),
        ),
        migrations.AlterField(
            model_name='toolcategory',
            name='name',
            field=models.CharField(default='未分类', max_length=50, unique=True, verbose_name='分类名称'),
        ),
        migrations.AlterField(
            model_name='toolcategory',
            name='slug',
            field=models.SlugField(default='default-category', unique=True, verbose_name='分类标识'),
        ),
    ]
