# Generated by Django 5.2.9 on 2026-01-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0003_add_teacher_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="grade",
            field=models.CharField(
                blank=True,
                default="2024",
                max_length=50,
                null=True,
                verbose_name="年级",
            ),
        ),
    ]
